services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:1.91.3
    container_name: n8n
    restart: unless-stopped
    environment:
      - N8N_PORT=5678
      - N8N_HOST=${N8N_HOST}
      - N8N_WEBHOOK=${N8N_WEBHOOK}
      - WEBHOOK_URL=https://${N8N_WEBHOOK}/
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    command:
      - "tunnel" 
      - "--no-autoupdate"
      - "run"
      - "--token" 
      - "${CLOUDFLARE_TUNNEL_TOKEN}"
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
    ports:
      - "8191:8191"

volumes:
  n8n_data:
    external: true
